# Generated by Django 3.1 on 2020-08-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boolean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('both_false', models.BooleanField()),
                ('both_true', models.BooleanField(blank=True, null=True)),
                ('null_true', models.BooleanField(null=True)),
                ('blank_true', models.BooleanField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('both_false', models.BooleanField(choices=[(True, 'Yes!'), (False, 'No!')])),
                ('both_true', models.BooleanField(blank=True, choices=[(True, 'Yes!'), (False, 'No!')], null=True)),
                ('null_true', models.BooleanField(choices=[(True, 'Yes!'), (False, 'No!')], null=True)),
                ('blank_true', models.BooleanField(blank=True, choices=[(True, 'Yes!'), (False, 'No!')])),
            ],
        ),
        migrations.CreateModel(
            name='ChoicesAndDefault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('both_false', models.BooleanField(choices=[(True, 'Yes!'), (False, 'No!')], default=True)),
                ('both_true', models.BooleanField(blank=True, choices=[(True, 'Yes!'), (False, 'No!')], default=True, null=True)),
                ('null_true', models.BooleanField(choices=[(True, 'Yes!'), (False, 'No!')], default=True, null=True)),
                ('blank_true', models.BooleanField(blank=True, choices=[(True, 'Yes!'), (False, 'No!')], default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Default',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('both_false', models.BooleanField(default=True)),
                ('both_true', models.BooleanField(blank=True, default=True, null=True)),
                ('null_true', models.BooleanField(default=True, null=True)),
                ('blank_true', models.BooleanField(blank=True, default=True)),
            ],
        ),
    ]
